
import type { Product } from './types';
import { placeholderImages } from './placeholder-images';

const getImage = (id: string, seed: string) => {
  const image = placeholderImages.find(img => img.id === id);
  return {
    url: image?.imageUrl ?? `https://picsum.photos/seed/${seed}/600/400`,
    hint: image?.imageHint ?? 'placeholder'
  }
}

export const allProducts: Product[] = [
  // Bags (15)
  {
    id: 'bag_001',
    name: 'Chocolaty Travel Bag',
    description: 'A stylish and durable travel bag.',
    longDescription: 'A stylish and durable travel bag perfect for weekend getaways.',
    price: 120.00,
    image: getImage('bag1', 'bag1').url,
    imageHint: getImage('bag1', 'bag1').hint,
  },
  {
    id: 'bag_002',
    name: 'Classy Brown Handbag',
    description: 'An elegant brown handbag for everyday use.',
    longDescription: 'An elegant brown handbag for everyday use, crafted from premium leather.',
    price: 85.00,
    image: getImage('bag2', 'bag2').url,
    imageHint: getImage('bag2', 'bag2').hint,
  },
  {
    id: 'bag_003',
    name: 'Ethnic Print White Tote',
    description: 'A beautiful white tote bag with an ethnic print.',
    longDescription: 'A beautiful white tote bag with an ethnic print, spacious and fashionable.',
    price: 65.00,
    image: getImage('bag3', 'bag3').url,
    imageHint: getImage('bag3', 'bag3').hint,
  },
  {
    id: 'bag_004',
    name: 'Crisp White And Blue Sling Bag',
    description: 'A chic sling bag in white and blue.',
    longDescription: 'A chic sling bag in white and blue, perfect for a day out.',
    price: 55.00,
    image: getImage('bag4', 'bag4').url,
    imageHint: getImage('bag4', 'bag4').hint,
  },
  {
    id: 'bag_005',
    name: 'Tan Brown Textured Bag',
    description: 'A textured tan brown bag with a classic look.',
    longDescription: 'A textured tan brown bag with a classic look, versatile for any occasion.',
    price: 95.00,
    image: getImage('bag5', 'bag5').url,
    imageHint: getImage('bag5', 'bag5').hint,
  },
  {
    id: 'bag_006',
    name: 'Chic Gray Cicular Bag',
    description: 'A unique circular bag in a chic gray color.',
    longDescription: 'A unique circular bag in a chic gray color, a true statement piece.',
    price: 75.00,
    image: getImage('bag6', 'bag6').url,
    imageHint: getImage('bag6', 'bag6').hint,
  },
  {
    id: 'bag_007',
    name: 'Embellished Black Sling Bag',
    description: 'A black sling bag with beautiful embellishments.',
    longDescription: 'A black sling bag with beautiful embellishments, perfect for evenings.',
    price: 80.00,
    image: getImage('bag7', 'bag7').url,
    imageHint: getImage('bag7', 'bag7').hint,
  },
  {
    id: 'bag_008',
    name: 'Futuristic Silver Handbag',
    description: 'A handbag with a futuristic silver design.',
    longDescription: 'A handbag with a futuristic silver design, for a bold fashion statement.',
    price: 110.00,
    image: getImage('bag8', 'bag8').url,
    imageHint: getImage('bag8', 'bag8').hint,
  },
    {
    id: 'bag_009',
    name: 'Classic Bag Sports Bag',
    description: 'A classic sports bag for all your gear.',
    longDescription: 'A classic sports bag for all your gear, spacious and durable.',
    price: 70.00,
    image: getImage('bag9', 'bag9').url,
    imageHint: getImage('bag9', 'bag9').hint,
  },
  {
    id: 'bag_010',
    name: 'Cool Black and Pink Gym Bag',
    description: 'A stylish gym bag in black and pink.',
    longDescription: 'A stylish gym bag in black and pink, combining fashion and function.',
    price: 60.00,
    image: getImage('bag10', 'bag10').url,
    imageHint: getImage('bag10', 'bag10').hint,
  },
  {
    id: 'bag_011',
    name: 'Sleek Green and Black Bag',
    description: 'A sleek bag in green and black.',
    longDescription: 'A sleek bag in green and black, modern and minimalist.',
    price: 78.00,
    image: getImage('bag11', 'bag11').url,
    imageHint: getImage('bag11', 'bag11').hint,
  },
  {
    id: 'bag_012',
    name: 'Black and Metallic Gray Colour Bag',
    description: 'A stylish bag in black and metallic gray.',
    longDescription: 'A stylish bag in black and metallic gray, perfect for a modern look.',
    price: 90.00,
    image: getImage('bag12', 'bag12').url,
    imageHint: getImage('bag12', 'bag12').hint,
  },
  {
    id: 'bag_013',
    name: 'Sturdy Hiking Backpack',
    description: 'A durable backpack for all your adventures.',
    longDescription: 'With multiple compartments and weather-resistant material, this backpack is perfect for hiking.',
    price: 150.00,
    image: getImage('bag13', 'bag13').url,
    imageHint: getImage('bag13', 'bag13').hint,
  },
  {
    id: 'bag_014',
    name: 'Sleek Laptop Bag',
    description: 'A professional bag to carry your tech.',
    longDescription: 'A sleek and padded laptop bag that fits up to a 15-inch laptop, with extra pockets for accessories.',
    price: 80.00,
    image: getImage('bag14', 'bag14').url,
    imageHint: getImage('bag14', 'bag14').hint,
  },
  {
    id: 'bag_015',
    name: 'Versatile Messenger Bag',
    description: 'A stylish messenger bag for daily use.',
    longDescription: 'This messenger bag is perfect for work or school, with an adjustable strap and plenty of room.',
    price: 70.00,
    image: getImage('bag15', 'bag15').url,
    imageHint: getImage('bag15', 'bag15').hint,
  },

  // Caps (15)
  {
    id: 'cap_001',
    name: 'Classic Baseball Cap',
    description: 'A timeless baseball cap for any casual occasion.',
    longDescription: 'Made from 100% cotton, this adjustable baseball cap offers comfort and style.',
    price: 25.00,
    image: getImage('cap1', 'cap1').url,
    imageHint: getImage('cap1', 'cap1').hint,
  },
  {
    id: 'cap_002',
    name: 'Wool Beanie',
    description: 'Stay warm with this soft wool beanie.',
    longDescription: 'A soft, comfortable wool beanie, perfect for cold weather. One size fits all.',
    price: 30.00,
    image: getImage('cap2', 'cap2').url,
    imageHint: getImage('cap2', 'cap2').hint,
  },
  {
    id: 'cap_003',
    name: 'Snapback Hat',
    description: 'A stylish snapback with a flat brim.',
    longDescription: 'This snapback hat features a modern design with an adjustable strap for a perfect fit.',
    price: 35.00,
    image: getImage('cap3', 'cap3').url,
    imageHint: getImage('cap3', 'cap3').hint,
  },
  {
    id: 'cap_004',
    name: 'Bucket Hat',
    description: 'A trendy bucket hat for sun protection.',
    longDescription: 'A lightweight and breathable bucket hat, ideal for sunny days and outdoor activities.',
    price: 28.00,
    image: getImage('cap4', 'cap4').url,
    imageHint: getImage('cap4', 'cap4').hint,
  },
  {
    id: 'cap_005',
    name: 'Trucker Hat',
    description: 'A classic trucker hat with a mesh back.',
    longDescription: 'This trucker hat offers a vintage look with a breathable mesh back for added comfort.',
    price: 22.00,
    image: getImage('cap5', 'cap5').url,
    imageHint: getImage('cap5', 'cap5').hint,
  },
  {
    id: 'cap_006',
    name: 'Flat Cap',
    description: 'A stylish flat cap for a classic look.',
    longDescription: 'This flat cap is made from a wool blend and offers a timeless, sophisticated look.',
    price: 40.00,
    image: getImage('cap6', 'cap6').url,
    imageHint: getImage('cap6', 'cap6').hint,
  },
  {
    id: 'cap_007',
    name: 'Newsboy Cap',
    description: 'A vintage-style newsboy cap.',
    longDescription: 'This newsboy cap has a classic eight-panel design and a button top for a vintage feel.',
    price: 38.00,
    image: getImage('cap7', 'cap7').url,
    imageHint: getImage('cap7', 'cap7').hint,
  },
  {
    id: 'cap_008',
    name: 'Sun Visor',
    description: 'A sporty sun visor for outdoor activities.',
    longDescription: 'Keep the sun out of your eyes with this adjustable and lightweight sun visor.',
    price: 18.00,
    image: getImage('cap8', 'cap8').url,
    imageHint: getImage('cap8', 'cap8').hint,
  },
  {
    id: 'cap_009',
    name: 'Beret',
    description: 'A classic wool beret for a touch of Parisian chic.',
    longDescription: 'This wool beret is a timeless accessory that adds a touch of elegance to any outfit.',
    price: 32.00,
    image: getImage('cap9', 'cap9').url,
    imageHint: getImage('cap9', 'cap9').hint,
  },
  {
    id: 'cap_010',
    name: 'Fedora',
    description: 'A stylish fedora for a sophisticated look.',
    longDescription: 'This classic fedora is made from high-quality felt and features a stylish ribbon band.',
    price: 55.00,
    image: getImage('cap10', 'cap10').url,
    imageHint: getImage('cap10', 'cap10').hint,
  },
  {
    id: 'cap_011',
    name: 'Trapper Hat',
    description: 'A warm trapper hat for extreme cold.',
    longDescription: 'This trapper hat features faux fur lining and ear flaps to keep you warm in the coldest weather.',
    price: 48.00,
    image: getImage('cap11', 'cap11').url,
    imageHint: getImage('cap11', 'cap11').hint,
  },
  {
    id: 'cap_012',
    name: 'Pom-Pom Beanie',
    description: 'A fun and stylish beanie with a pom-pom.',
    longDescription: 'This knit beanie is topped with a faux fur pom-pom for a playful and cozy winter look.',
    price: 28.00,
    image: getImage('cap12', 'cap12').url,
    imageHint: getImage('cap12', 'cap12').hint,
  },
  {
    id: 'cap_013',
    name: 'Dad Hat',
    description: 'A comfortable and casual dad hat.',
    longDescription: 'This relaxed-fit dad hat is made from soft cotton and has an adjustable strap for a perfect fit.',
    price: 24.00,
    image: getImage('cap13', 'cap13').url,
    imageHint: getImage('cap13', 'cap13').hint,
  },
  {
    id: 'cap_014',
    name: 'Wide-Brim Sun Hat',
    description: 'A stylish hat for maximum sun protection.',
    longDescription: 'This wide-brim sun hat is perfect for the beach or garden, offering excellent protection from the sun.',
    price: 45.00,
    image: getImage('cap14', 'cap14').url,
    imageHint: getImage('cap14', 'cap14').hint,
  },
  {
    id: 'cap_015',
    name: 'Simple Black Cap',
    description: 'A minimalist black cap for any occasion.',
    longDescription: 'This simple black cap is a versatile accessory that complements any casual outfit.',
    price: 20.00,
    image: getImage('cap15', 'cap15').url,
    imageHint: getImage('cap15', 'cap15').hint,
  },
  
  // Scarves (15)
  {
    id: 'scarf_001',
    name: 'Cozy Wool Scarf',
    description: 'A warm and soft wool scarf.',
    longDescription: 'Stay warm and stylish with this cozy wool scarf, perfect for chilly days.',
    price: 45.00,
    image: getImage('scarf1', 'scarf1').url,
    imageHint: getImage('scarf1', 'scarf1').hint,
  },
  {
    id: 'scarf_002',
    name: 'Floral Silk Scarf',
    description: 'A lightweight silk scarf with a beautiful floral print.',
    longDescription: 'Add a touch of elegance to your outfit with this beautiful floral print silk scarf.',
    price: 35.00,
    image: getImage('scarf2', 'scarf2').url,
    imageHint: getImage('scarf2', 'scarf2').hint,
  },
  {
    id: 'scarf_003',
    name: 'Stylish Infinity Scarf',
    description: 'A versatile and stylish infinity scarf.',
    longDescription: 'This infinity scarf can be worn in multiple ways and adds a fashionable touch to any look.',
    price: 30.00,
    image: getImage('scarf3', 'scarf3').url,
    imageHint: getImage('scarf3', 'scarf3').hint,
  },
  {
    id: 'scarf_004',
    name: 'Plaid Cashmere Scarf',
    description: 'A luxurious plaid cashmere scarf.',
    longDescription: 'Experience the softness and warmth of this classic plaid cashmere scarf.',
    price: 85.00,
    image: getImage('scarf4', 'scarf4').url,
    imageHint: getImage('scarf4', 'scarf4').hint,
  },
  {
    id: 'scarf_005',
    name: 'Chunky Knit Scarf',
    description: 'A very warm and cozy chunky knit scarf.',
    longDescription: 'Brave the cold with this extra-warm and stylish chunky knit scarf.',
    price: 50.00,
    image: getImage('scarf5', 'scarf5').url,
    imageHint: getImage('scarf5', 'scarf5').hint,
  },
  {
    id: 'scarf_006',
    name: 'Fringed Pashmina Scarf',
    description: 'An elegant pashmina scarf with fringe details.',
    longDescription: 'This elegant pashmina scarf is perfect for formal occasions or a stylish everyday look.',
    price: 60.00,
    image: getImage('scarf6', 'scarf6').url,
    imageHint: getImage('scarf6', 'scarf6').hint,
  },
  {
    id: 'scarf_007',
    name: 'Cotton Bandana Scarf',
    description: 'A versatile cotton bandana scarf.',
    longDescription: 'This cotton bandana can be worn as a neck scarf, headband, or accessory.',
    price: 15.00,
    image: getImage('scarf7', 'scarf7').url,
    imageHint: getImage('scarf7', 'scarf7').hint,
  },
  {
    id: 'scarf_008',
    name: 'Neck Gaiter Scarf',
    description: 'A practical neck gaiter for outdoor activities.',
    longDescription: 'This neck gaiter is perfect for sports and outdoor adventures, offering protection from the elements.',
    price: 20.00,
    image: getImage('scarf8', 'scarf8').url,
    imageHint: getImage('scarf8', 'scarf8').hint,
  },
  {
    id: 'scarf_009',
    name: 'Square Satin Scarf',
    description: 'A chic and silky square satin scarf.',
    longDescription: 'This square satin scarf can be tied in various ways to accessorize your look.',
    price: 25.00,
    image: getImage('scarf9', 'scarf9').url,
    imageHint: getImage('scarf9', 'scarf9').hint,
  },
  {
    id: 'scarf_010',
    name: 'Fleece Winter Scarf',
    description: 'A soft and warm fleece scarf for winter.',
    longDescription: 'Stay extra warm with this soft and insulating fleece winter scarf.',
    price: 28.00,
    image: getImage('scarf10', 'scarf10').url,
    imageHint: getImage('scarf10', 'scarf10').hint,
  },
  {
    id: 'scarf_011',
    name: 'Lightweight Linen Scarf',
    description: 'A breathable linen scarf for warmer weather.',
    longDescription: 'This lightweight linen scarf is perfect for a breezy and stylish summer accessory.',
    price: 32.00,
    image: getImage('scarf11', 'scarf11').url,
    imageHint: getImage('scarf11', 'scarf11').hint,
  },
  {
    id: 'scarf_012',
    name: 'Shawl Wrap Scarf',
    description: 'A large and versatile shawl wrap scarf.',
    longDescription: 'This large shawl wrap can be worn as a scarf, shawl, or wrap for any occasion.',
    price: 55.00,
    image: getImage('scarf12', 'scarf12').url,
    imageHint: getImage('scarf12', 'scarf12').hint,
  },
  {
    id: 'scarf_013',
    name: 'Hooded Scarf',
    description: 'A unique and practical hooded scarf.',
    longDescription: 'This hooded scarf combines the warmth of a hat and a scarf in one stylish piece.',
    price: 48.00,
    image: getImage('scarf13', 'scarf13').url,
    imageHint: getImage('scarf13', 'scarf13').hint,
  },
  {
    id: 'scarf_014',
    name: 'Triangular Kerchief Scarf',
    description: 'A fashionable triangular kerchief scarf.',
    longDescription: 'This triangular kerchief adds a trendy touch to any outfit, worn around the neck or as a headscarf.',
    price: 22.00,
    image: getImage('scarf14', 'scarf14').url,
    imageHint: getImage('scarf14', 'scarf14').hint,
  },
  {
    id: 'scarf_015',
    name: 'Vintage-Style Scarf',
    description: 'A scarf with a classic vintage print.',
    longDescription: 'This vintage-style scarf features a timeless print that adds a touch of retro charm.',
    price: 38.00,
    image: getImage('scarf15', 'scarf15').url,
    imageHint: getImage('scarf15', 'scarf15').hint,
  },
  
  // Sleepwear (15)
  {
    id: 'sleepwear_001',
    name: 'Cotton Pajama Set',
    description: 'A comfortable and breathable cotton pajama set.',
    longDescription: 'Enjoy a restful night\'s sleep in this soft and breathable 100% cotton pajama set.',
    price: 50.00,
    image: getImage('sleepwear1', 'sleepwear1').url,
    imageHint: getImage('sleepwear1', 'sleepwear1').hint,
  },
  {
    id: 'sleepwear_002',
    name: 'Silk Nightgown',
    description: 'A luxurious and elegant silk nightgown.',
    longDescription: 'Feel elegant and comfortable in this beautiful nightgown made from pure silk.',
    price: 95.00,
    image: getImage('sleepwear2', 'sleepwear2').url,
    imageHint: getImage('sleepwear2', 'sleepwear2').hint,
  },
  {
    id: 'sleepwear_003',
    name: 'Flannel Pajama Set',
    description: 'A cozy flannel pajama set for cold nights.',
    longDescription: 'Stay warm and cozy on cold nights with this classic flannel pajama set.',
    price: 60.00,
    image: getImage('sleepwear3', 'sleepwear3').url,
    imageHint: getImage('sleepwear3', 'sleepwear3').hint,
  },
  {
    id: 'sleepwear_004',
    name: 'Plush Fleece Robe',
    description: 'A soft and warm plush fleece robe.',
    longDescription: 'Wrap yourself in luxury with this incredibly soft and warm plush fleece robe.',
    price: 75.00,
    image: getImage('sleepwear4', 'sleepwear4').url,
    imageHint: getImage('sleepwear4', 'sleepwear4').hint,
  },
  {
    id: 'sleepwear_005',
    name: 'Short Pajama Set',
    description: 'A cute and comfortable short pajama set.',
    longDescription: 'This short pajama set includes a tank top and shorts, perfect for warmer nights.',
    price: 40.00,
    image: getImage('sleepwear5', 'sleepwear5').url,
    imageHint: getImage('sleepwear5', 'sleepwear5').hint,
  },
  {
    id: 'sleepwear_006',
    name: 'Satin Chemise',
    description: 'An elegant satin chemise for a touch of glamour.',
    longDescription: 'This beautiful satin chemise is perfect for a special occasion or a luxurious night in.',
    price: 55.00,
    image: getImage('sleepwear6', 'sleepwear6').url,
    imageHint: getImage('sleepwear6', 'sleepwear6').hint,
  },
  {
    id: 'sleepwear_007',
    name: 'Onesie Pajama',
    description: 'A fun and playful onesie pajama.',
    longDescription: 'Get comfortable and have some fun with this cozy and playful onesie pajama.',
    price: 65.00,
    image: getImage('sleepwear7', 'sleepwear7').url,
    imageHint: getImage('sleepwear7', 'sleepwear7').hint,
  },
  {
    id: 'sleepwear_008',
    name: 'Thermal Pajama Set',
    description: 'A warm thermal pajama set for extra cold nights.',
    longDescription: 'This thermal pajama set provides extra warmth and comfort during the coldest winter nights.',
    price: 68.00,
    image: getImage('sleepwear8', 'sleepwear8').url,
    imageHint: getImage('sleepwear8', 'sleepwear8').hint,
  },
  {
    id: 'sleepwear_009',
    name: 'Babydoll Nightie',
    description: 'A cute and flirty babydoll nightie.',
    longDescription: 'This babydoll nightie is a playful and comfortable choice for a stylish night\'s sleep.',
    price: 48.00,
    image: getImage('sleepwear9', 'sleepwear9').url,
    imageHint: getImage('sleepwear9', 'sleepwear9').hint,
  },
  {
    id: 'sleepwear_010',
    name: 'Jersey Nightshirt',
    description: 'A soft and comfortable jersey nightshirt.',
    longDescription: 'This lightweight jersey nightshirt is perfect for a comfortable and relaxed sleep.',
    price: 42.00,
    image: getImage('sleepwear10', 'sleepwear10').url,
    imageHint: getImage('sleepwear10', 'sleepwear10').hint,
  },
  {
    id: 'sleepwear_011',
    name: 'Long-Sleeved Pajama Top',
    description: 'A cozy long-sleeved pajama top.',
    longDescription: 'This cozy long-sleeved top is perfect for mixing and matching with your favorite pajama bottoms.',
    price: 35.00,
    image: getImage('sleepwear11', 'sleepwear11').url,
    imageHint: getImage('sleepwear11', 'sleepwear11').hint,
  },
  {
    id: 'sleepwear_012',
    name: 'Lounge Pants',
    description: 'Comfortable pants for lounging or sleeping.',
    longDescription: 'These soft and comfortable lounge pants are perfect for a lazy day at home or a good night\'s sleep.',
    price: 38.00,
    image: getImage('sleepwear12', 'sleepwear12').url,
    imageHint: getImage('sleepwear12', 'sleepwear12').hint,
  },
  {
    id: 'sleepwear_013',
    name: 'Sleep Romper',
    description: 'A stylish and comfortable sleep romper.',
    longDescription: 'This sleep romper combines style and comfort for a modern and chic sleepwear option.',
    price: 45.00,
    image: getImage('sleepwear13', 'sleepwear13').url,
    imageHint: getImage('sleepwear13', 'sleepwear13').hint,
  },
  {
    id: 'sleepwear_014',
    name: 'Waffle-Knit Sleep Set',
    description: 'A cozy and textured waffle-knit sleep set.',
    longDescription: 'This waffle-knit sleep set is perfect for a comfortable and stylish night in.',
    price: 58.00,
    image: getImage('sleepwear14', 'sleepwear14').url,
    imageHint: getImage('sleepwear14', 'sleepwear14').hint,
  },
  {
    id: 'sleepwear_015',
    name: 'Hooded Sleep Sweatshirt',
    description: 'A cozy hooded sweatshirt for sleeping or lounging.',
    longDescription: 'Stay warm and comfortable in this hooded sleep sweatshirt, perfect for relaxing at home.',
    price: 52.00,
    image: getImage('sleepwear15', 'sleepwear15').url,
    imageHint: getImage('sleepwear15', 'sleepwear15').hint,
  },
  
  // Socks (15)
  {
    id: 'sock_001',
    name: 'Classic Crew Socks',
    description: 'A pack of comfortable and durable crew socks.',
    longDescription: 'These classic crew socks are made from a soft cotton blend for all-day comfort.',
    price: 15.00,
    image: getImage('sock1', 'sock1').url,
    imageHint: getImage('sock1', 'sock1').hint,
  },
  {
    id: 'sock_002',
    name: 'No-Show Ankle Socks',
    description: 'A pack of low-cut, no-show ankle socks.',
    longDescription: 'These ankle socks are designed to stay hidden while providing comfort and support.',
    price: 12.00,
    image: getImage('sock2', 'sock2').url,
    imageHint: getImage('sock2', 'sock2').hint,
  },
  {
    id: 'sock_003',
    name: 'Cozy Wool Socks',
    description: 'A pair of warm and cozy wool socks.',
    longDescription: 'Keep your feet warm and comfortable in these soft and insulating wool socks.',
    price: 18.00,
    image: getImage('sock3', 'sock3').url,
    imageHint: getImage('sock3', 'sock3').hint,
  },
  {
    id: 'sock_004',
    name: 'Athletic Performance Socks',
    description: 'A pair of high-performance athletic socks.',
    longDescription: 'These athletic socks provide cushioning and moisture-wicking to keep you comfortable during workouts.',
    price: 20.00,
    image: getImage('sock4', 'sock4').url,
    imageHint: getImage('sock4', 'sock4').hint,
  },
  {
    id: 'sock_005',
    name: 'Patterned Dress Socks',
    description: 'A pair of stylish patterned dress socks.',
    longDescription: 'Add a pop of color and personality to your outfit with these patterned dress socks.',
    price: 16.00,
    image: getImage('sock5', 'sock5').url,
    imageHint: getImage('sock5', 'sock5').hint,
  },
  {
    id: 'sock_006',
    name: 'Compression Socks',
    description: 'A pair of compression socks for improved circulation.',
    longDescription: 'These compression socks are designed to improve blood flow and reduce swelling.',
    price: 25.00,
    image: getImage('sock6', 'sock6').url,
    imageHint: getImage('sock6', 'sock6').hint,
  },
  {
    id: 'sock_007',
    name: 'Fuzzy Slipper Socks',
    description: 'A pair of soft and fuzzy slipper socks.',
    longDescription: 'Keep your feet warm and cozy at home with these fuzzy slipper socks with non-slip grips.',
    price: 22.00,
    image: getImage('sock7', 'sock7').url,
    imageHint: getImage('sock7', 'sock7').hint,
  },
  {
    id: 'sock_008',
    name: 'Quarter-Length Socks',
    description: 'A pack of comfortable quarter-length socks.',
    longDescription: 'These quarter-length socks are perfect for everyday wear and provide a comfortable fit.',
    price: 14.00,
    image: getImage('sock8', 'sock8').url,
    imageHint: getImage('sock8', 'sock8').hint,
  },
  {
    id: 'sock_009',
    name: 'Knee-High Socks',
    description: 'A pair of stylish knee-high socks.',
    longDescription: 'These knee-high socks add a fashionable touch to any outfit, from skirts to shorts.',
    price: 18.00,
    image: getImage('sock9', 'sock9').url,
    imageHint: getImage('sock9', 'sock9').hint,
  },
  {
    id: 'sock_010',
    name: 'Novelty Graphic Socks',
    description: 'A pair of fun and quirky novelty graphic socks.',
    longDescription: 'Show off your personality with these fun and colorful novelty graphic socks.',
    price: 16.00,
    image: getImage('sock10', 'sock10').url,
    imageHint: getImage('sock10', 'sock10').hint,
  },
  {
    id: 'sock_011',
    name: 'Thermal Boot Socks',
    description: 'A pair of warm thermal socks for boots.',
    longDescription: 'These thermal boot socks are designed to keep your feet warm and comfortable in cold weather.',
    price: 24.00,
    image: getImage('sock11', 'sock11').url,
    imageHint: getImage('sock11', 'sock11').hint,
  },
  {
    id: 'sock_012',
    name: 'Thigh-High Socks',
    description: 'A pair of fashionable thigh-high socks.',
    longDescription: 'These thigh-high socks make a bold fashion statement and can be paired with dresses or skirts.',
    price: 20.00,
    image: getImage('sock12', 'sock12').url,
    imageHint: getImage('sock12', 'sock12').hint,
  },
  {
    id: 'sock_013',
    name: 'Tabi Socks',
    description: 'A pair of traditional Japanese tabi socks.',
    longDescription: 'These tabi socks have a split-toe design, perfect for wearing with traditional Japanese footwear.',
    price: 15.00,
    image: getImage('sock13', 'sock13').url,
    imageHint: getImage('sock13', 'sock13').hint,
  },
  {
    id: 'sock_014',
    name: 'Argyle Socks',
    description: 'A pair of classic argyle dress socks.',
    longDescription: 'These argyle socks add a touch of classic style to any formal or casual outfit.',
    price: 17.00,
    image: getImage('sock14', 'sock14').url,
    imageHint: getImage('sock14', 'sock14').hint,
  },
  {
    id: 'sock_015',
    name: 'Cotton Tube Socks',
    description: 'A pack of retro-style cotton tube socks.',
    longDescription: 'These cotton tube socks have a vintage athletic look and offer great comfort.',
    price: 16.00,
    image: getImage('sock15', 'sock15').url,
    imageHint: getImage('sock15', 'sock15').hint,
  },
  
  // Towels (15)
  {
    id: 'towel_001',
    name: 'Plush Cotton Bath Towel',
    description: 'A soft and absorbent plush cotton bath towel.',
    longDescription: 'Wrap yourself in comfort with this highly absorbent and soft plush cotton bath towel.',
    price: 25.00,
    image: getImage('towel1', 'towel1').url,
    imageHint: getImage('towel1', 'towel1').hint,
  },
  {
    id: 'towel_002',
    name: 'Soft Hand Towels',
    description: 'A set of soft and durable hand towels.',
    longDescription: 'This set of hand towels is perfect for the bathroom or kitchen, offering softness and durability.',
    price: 18.00,
    image: getImage('towel2', 'towel2').url,
    imageHint: getImage('towel2', 'towel2').hint,
  },
  {
    id: 'towel_003',
    name: 'Quick-Dry Beach Towel',
    description: 'A large and lightweight quick-dry beach towel.',
    longDescription: 'This beach towel is extra-large, lightweight, and dries quickly, perfect for a day at the beach.',
    price: 30.00,
    image: getImage('towel3', 'towel3').url,
    imageHint: getImage('towel3', 'towel3').hint,
  },
  {
    id: 'towel_004',
    name: 'Egyptian Cotton Towel Set',
    description: 'A luxurious set of Egyptian cotton towels.',
    longDescription: 'Indulge in the luxury of this Egyptian cotton towel set, known for its superior softness and absorbency.',
    price: 75.00,
    image: getImage('towel4', 'towel4').url,
    imageHint: getImage('towel4', 'towel4').hint,
  },
  {
    id: 'towel_005',
    name: 'Microfiber Travel Towel',
    description: 'A compact and lightweight microfiber travel towel.',
    longDescription: 'This microfiber towel is perfect for travel, camping, or the gym, as it is compact and dries quickly.',
    price: 20.00,
    image: getImage('towel5', 'towel5').url,
    imageHint: getImage('towel5', 'towel5').hint,
  },
  {
    id: 'towel_006',
    name: 'Washcloths Set',
    description: 'A set of soft and gentle washcloths.',
    longDescription: 'This set of washcloths is made from soft cotton, perfect for gentle cleansing.',
    price: 12.00,
    image: getImage('towel6', 'towel6').url,
    imageHint: getImage('towel6', 'towel6').hint,
  },
  {
    id: 'towel_007',
    name: 'Hooded Towel for Kids',
    description: 'A fun and cozy hooded towel for kids.',
    longDescription: 'Make bath time fun with this soft and absorbent hooded towel, perfect for kids.',
    price: 28.00,
    image: getImage('towel7', 'towel7').url,
    imageHint: getImage('towel7', 'towel7').hint,
  },
  {
    id: 'towel_008',
    name: 'Kitchen Towel Set',
    description: 'A set of absorbent and stylish kitchen towels.',
    longDescription: 'This set of kitchen towels is perfect for drying dishes and hands, with a stylish design.',
    price: 16.00,
    image: getImage('towel8', 'towel8').url,
    imageHint: getImage('towel8', 'towel8').hint,
  },
  {
    id: 'towel_009',
    name: 'Gym Towel',
    description: 'A compact and absorbent gym towel.',
    longDescription: 'This gym towel is designed to be lightweight and absorbent, perfect for your workout.',
    price: 15.00,
    image: getImage('towel9', 'towel9').url,
    imageHint: getImage('towel9', 'towel9').hint,
  },
  {
    id: 'towel_010',
    name: 'Turkish Peshtemal Towel',
    description: 'A traditional and versatile Turkish peshtemal towel.',
    longDescription: 'This peshtemal towel is lightweight, absorbent, and can be used as a bath towel, beach towel, or wrap.',
    price: 35.00,
    image: getImage('towel10', 'towel10').url,
    imageHint: getImage('towel10', 'towel10').hint,
  },
  {
    id: 'towel_011',
    name: 'Waffle-Weave Bath Towel',
    description: 'A textured and absorbent waffle-weave bath towel.',
    longDescription: 'This waffle-weave towel is not only absorbent but also has a unique texture that feels great on the skin.',
    price: 28.00,
    image: getImage('towel11', 'towel11').url,
    imageHint: getImage('towel11', 'towel11').hint,
  },
  {
    id: 'towel_012',
    name: 'Fingertip Towel',
    description: 'A small and decorative fingertip towel.',
    longDescription: 'This fingertip towel is perfect for guest bathrooms, adding a touch of elegance and style.',
    price: 10.00,
    image: getImage('towel12', 'towel12').url,
    imageHint: getImage('towel12', 'towel12').hint,
  },
  {
    id: 'towel_013',
    name: 'Large Bath Sheet',
    description: 'An oversized and luxurious bath sheet.',
    longDescription: 'Wrap yourself in luxury with this oversized bath sheet, offering maximum coverage and comfort.',
    price: 40.00,
    image: getImage('towel13', 'towel13').url,
    imageHint: getImage('towel13', 'towel13').hint,
  },
  {
    id: 'towel_014',
    name: 'Bamboo Towel Set',
    description: 'A soft and eco-friendly bamboo towel set.',
    longDescription: 'This towel set is made from bamboo fibers, making it incredibly soft, absorbent, and eco-friendly.',
    price: 80.00,
    image: getImage('towel14', 'towel14').url,
    imageHint: getImage('towel14', 'towel14').hint,
  },
  {
    id: 'towel_015',
    name: 'Spa Towel Wrap',
    description: 'A comfortable and convenient spa towel wrap.',
    longDescription: 'This spa wrap is perfect for after a shower or at the spa, with an adjustable closure for a secure fit.',
    price: 22.00,
    image: getImage('towel15', 'towel15').url,
    imageHint: getImage('towel15', 'towel15').hint,
  },

  // T-Shirts (5)
  {
    id: 't-shirt_001',
    name: 'Men\'s Crewneck T-Shirt',
    description: 'A basic essential for any wardrobe.',
    longDescription: 'Crafted from soft, breathable cotton, this crewneck T-shirt offers a classic fit for everyday comfort.',
    price: 20.00,
    image: getImage('tshirt1', 'tshirt1').url,
    imageHint: getImage('tshirt1', 'tshirt1').hint,
  },
  {
    id: 't-shirt_002',
    name: 'Women\'s V-Neck T-Shirt',
    description: 'A flattering V-neck cut.',
    longDescription: 'This V-neck T-shirt is made from a soft cotton blend, providing a stylish and comfortable fit.',
    price: 22.00,
    image: getImage('tshirt2', 'tshirt2').url,
    imageHint: getImage('tshirt2', 'tshirt2').hint,
  },
  {
    id: 't-shirt_003',
    name: 'Graphic Print T-Shirt',
    description: 'A bold graphic print to make a statement.',
    longDescription: 'Featuring a unique graphic print, this T-shirt is perfect for adding a touch of personality to your look.',
    price: 28.00,
    image: getImage('tshirt3', 'tshirt3').url,
    imageHint: getImage('tshirt3', 'tshirt3').hint,
  },
  {
    id: 't-shirt_004',
    name: 'Polo T-Shirt',
    description: 'A classic polo for a smart-casual look.',
    longDescription: 'This polo T-shirt is made from high-quality piqué cotton, offering a refined yet comfortable style.',
    price: 45.00,
    image: getImage('tshirt4', 'tshirt4').url,
    imageHint: getImage('tshirt4', 'tshirt4').hint,
  },
  {
    id: 't-shirt_005',
    name: 'Long-Sleeve T-Shirt',
    description: 'Perfect for layering in cooler weather.',
    longDescription: 'This long-sleeve T-shirt is made from a soft and warm cotton fabric, ideal for transitional seasons.',
    price: 30.00,
    image: getImage('tshirt5', 'tshirt5').url,
    imageHint: getImage('tshirt5', 'tshirt5').hint,
  },
  // Hoodies (12)
  {
    id: 'hoodie_001',
    name: 'Plush Beige Coton Hoodie',
    description: 'A comfortable and stylish beige hoodie.',
    longDescription: 'Made from plush cotton, this beige hoodie offers both comfort and style, perfect for a casual look.',
    price: 60.00,
    image: getImage('hoodie1', 'hoodie1').url,
    imageHint: getImage('hoodie1', 'hoodie1').hint,
  },
  {
    id: 'hoodie_002',
    name: 'Men Flannel Hoodie',
    description: 'A trendy flannel hoodie for a rugged look.',
    longDescription: 'This flannel hoodie combines the warmth of a jacket with the comfort of a hoodie, ideal for outdoor adventures.',
    price: 75.00,
    image: getImage('hoodie2', 'hoodie2').url,
    imageHint: getImage('hoodie2', 'hoodie2').hint,
  },
  {
    id: 'hoodie_003',
    name: 'Light Gray Hoodie',
    description: 'A classic light gray hoodie for everyday wear.',
    longDescription: 'A versatile and comfortable light gray hoodie that pairs well with any outfit.',
    price: 55.00,
    image: getImage('hoodie3', 'hoodie3').url,
    imageHint: getImage('hoodie3', 'hoodie3').hint,
  },
  {
    id: 'hoodie_004',
    name: 'Gray and Canary Yellow Designer Hoodie',
    description: 'A striking designer hoodie in gray and yellow.',
    longDescription: 'Make a statement with this designer hoodie featuring a bold color-block design in gray and canary yellow.',
    price: 85.00,
    image: getImage('hoodie4', 'hoodie4').url,
    imageHint: getImage('hoodie4', 'hoodie4').hint,
  },
  {
    id: 'hoodie_005',
    name: 'Tomato Red and White Designer Hoodie',
    description: 'A vibrant designer hoodie in red and white.',
    longDescription: 'This eye-catching hoodie in tomato red and white is perfect for a sporty and stylish look.',
    price: 80.00,
    image: getImage('hoodie5', 'hoodie5').url,
    imageHint: getImage('hoodie5', 'hoodie5').hint,
  },
  {
    id: 'hoodie_006',
    name: 'Gray and pastel Green Designer Hoodie',
    description: 'A cool designer hoodie in gray and pastel green.',
    longDescription: 'A modern and stylish hoodie with a unique color combination of gray and pastel green.',
    price: 82.00,
    image: getImage('hoodie6', 'hoodie6').url,
    imageHint: getImage('hoodie6', 'hoodie6').hint,
  },
  {
    id: 'hoodie_007',
    name: 'White, Gray and Black Designer Hoodie',
    description: 'A sleek designer hoodie in a monochrome palette.',
    longDescription: 'This hoodie features a sophisticated color-block design in white, gray, and black for a modern aesthetic.',
    price: 90.00,
    image: getImage('hoodie7', 'hoodie7').url,
    imageHint: getImage('hoodie7', 'hoodie7').hint,
  },
  {
    id: 'hoodie_008',
    name: 'Black and Neon Trimmings Designer Hoodie',
    description: 'A black hoodie with vibrant neon details.',
    longDescription: 'Stand out with this black designer hoodie featuring bright neon green trimmings for a futuristic look.',
    price: 88.00,
    image: getImage('hoodie8', 'hoodie8').url,
    imageHint: getImage('hoodie8', 'hoodie8').hint,
  },
  {
    id: 'hoodie_009',
    name: 'Royal Blue and White Designer Hoodie',
    description: 'A classic designer hoodie in blue and white.',
    longDescription: 'This hoodie combines royal blue and white for a timeless and sporty look.',
    price: 85.00,
    image: getImage('hoodie9', 'hoodie9').url,
    imageHint: getImage('hoodie9', 'hoodie9').hint,
  },
  {
    id: 'hoodie_010',
    name: 'Red and Black Designer Hoodie',
    description: 'A bold designer hoodie in red and black.',
    longDescription: 'This hoodie features a powerful color combination of red and black, perfect for a confident look.',
    price: 85.00,
    image: getImage('hoodie10', 'hoodie10').url,
    imageHint: getImage('hoodie10', 'hoodie10').hint,
  },
  {
    id: 'hoodie_011',
    name: 'Black and Red Designer Hoodie',
    description: 'A sleek black hoodie with red accents.',
    longDescription: 'A stylish and modern black hoodie with striking red details for a sharp look.',
    price: 88.00,
    image: getImage('hoodie11', 'hoodie11').url,
    imageHint: getImage('hoodie11', 'hoodie11').hint,
  },
  {
    id: 'hoodie_012',
    name: 'Black and Blue Designer Hoodie',
    description: 'A cool designer hoodie in black and blue.',
    longDescription: 'This hoodie features a subtle yet stylish combination of black and blue, perfect for a relaxed look.',
    price: 85.00,
    image: getImage('hoodie12', 'hoodie12').url,
    imageHint: getImage('hoodie12', 'hoodie12').hint,
  },
   // Women's Dresses
  {
    id: 'dress_001',
    name: 'Floral Maxi Dress',
    description: 'A beautiful and flowing floral maxi dress.',
    longDescription: 'Perfect for summer days, this floral maxi dress is made from lightweight fabric and features a flattering silhouette.',
    price: 120.00,
    image: getImage('dress1', 'dress1').url,
    imageHint: getImage('dress1', 'dress1').hint,
  },
  {
    id: 'dress_002',
    name: 'Little Black Dress',
    description: 'A timeless and versatile little black dress.',
    longDescription: 'An essential for any wardrobe, this little black dress can be dressed up or down for any occasion.',
    price: 95.00,
    image: getImage('dress2', 'dress2').url,
    imageHint: getImage('dress2', 'dress2').hint,
  },
  {
    id: 'dress_003',
    name: 'Red Cocktail Dress',
    description: 'A stunning red cocktail dress for special events.',
    longDescription: 'Turn heads in this vibrant red cocktail dress, featuring a figure-hugging fit and elegant design.',
    price: 150.00,
    image: getImage('dress3', 'dress3').url,
    imageHint: getImage('dress3', 'dress3').hint,
  },

  // Women's Coats
  {
    id: 'coat_001',
    name: 'Classic Trench Coat',
    description: 'A timeless trench coat for a sophisticated look.',
    longDescription: 'This classic tan trench coat is a must-have for any season, offering both style and practicality.',
    price: 180.00,
    image: getImage('coat1', 'coat1').url,
    imageHint: getImage('coat1', 'coat1').hint,
  },
  {
    id: 'coat_002',
    name: 'Wool Peacoat',
    description: 'A warm and stylish wool peacoat.',
    longDescription: 'Stay warm in this classic double-breasted wool peacoat, perfect for colder weather.',
    price: 220.00,
    image: getImage('coat2', 'coat2').url,
    imageHint: getImage('coat2', 'coat2').hint,
  },
  {
    id: 'coat_003',
    name: 'Duster Coat',
    description: 'A chic and lightweight duster coat.',
    longDescription: 'This longline duster coat adds a layer of sophistication to any outfit, perfect for transitional weather.',
    price: 130.00,
    image: getImage('coat3', 'coat3').url,
    imageHint: getImage('coat3', 'coat3').hint,
  },

  // Women's Jackets
  {
    id: 'jacket_001',
    name: 'Denim Jacket',
    description: 'A versatile and timeless denim jacket.',
    longDescription: 'A classic wardrobe staple, this denim jacket can be paired with almost any outfit for a casual, cool look.',
    price: 90.00,
    image: getImage('jacket1', 'jacket1').url,
    imageHint: getImage('jacket1', 'jacket1').hint,
  },
  {
    id: 'jacket_002',
    name: 'Leather Moto Jacket',
    description: 'A sleek and edgy leather moto jacket.',
    longDescription: 'Add an edge to your look with this classic leather moto jacket, made from high-quality faux leather.',
    price: 160.00,
    image: getImage('jacket2', 'jacket2').url,
    imageHint: getImage('jacket2', 'jacket2').hint,
  },
  {
    id: 'jacket_003',
    name: 'Bomber Jacket',
    description: 'A trendy and comfortable bomber jacket.',
    longDescription: 'This stylish bomber jacket is perfect for a casual, sporty look, made from a lightweight material.',
    price: 110.00,
    image: getImage('jacket3', 'jacket3').url,
    imageHint: getImage('jacket3', 'jacket3').hint,
  },

  // Women's Top Wear
  {
    id: 'topwear_001',
    name: 'White Button-Down Shirt',
    description: 'A crisp and classic white button-down shirt.',
    longDescription: 'An essential piece for any wardrobe, this white button-down shirt is perfect for both professional and casual settings.',
    price: 65.00,
    image: getImage('topwear1', 'topwear1').url,
    imageHint: getImage('topwear1', 'topwear1').hint,
  },
  {
    id: 'topwear_002',
    name: 'Cashmere Sweater',
    description: 'A luxurious and soft cashmere sweater.',
    longDescription: 'Indulge in the softness of this beautiful cashmere sweater, perfect for staying warm and stylish.',
    price: 180.00,
    image: getImage('topwear2', 'topwear2').url,
    imageHint: getImage('topwear2', 'topwear2').hint,
  },
  {
    id: 'topwear_003',
    name: 'Striped T-Shirt',
    description: 'A classic and casual striped t-shirt.',
    longDescription: 'This timeless striped t-shirt is made from soft cotton and is perfect for everyday wear.',
    price: 40.00,
    image: getImage('topwear3', 'topwear3').url,
    imageHint: getImage('topwear3', 'topwear3').hint,
  },

  // Women's Leggings
  {
    id: 'leggings_001',
    name: 'High-Waisted Yoga Leggings',
    description: 'Comfortable and supportive high-waisted yoga leggings.',
    longDescription: 'These high-waisted leggings are perfect for yoga or any workout, offering support and flexibility.',
    price: 75.00,
    image: getImage('leggings1', 'leggings1').url,
    imageHint: getImage('leggings1', 'leggings1').hint,
  },
  {
    id: 'leggings_002',
    name: 'Faux Leather Leggings',
    description: 'Chic and stylish faux leather leggings.',
    longDescription: 'Elevate your look with these trendy faux leather leggings, perfect for a night out.',
    price: 85.00,
    image: getImage('leggings2', 'leggings2').url,
    imageHint: getImage('leggings2', 'leggings2').hint,
  },
  {
    id: 'leggings_003',
    name: 'Cotton Leggings',
    description: 'Basic and comfortable cotton leggings for daily wear.',
    longDescription: 'These soft and breathable cotton leggings are a wardrobe staple for everyday comfort.',
    price: 45.00,
    image: getImage('leggings3', 'leggings3').url,
    imageHint: getImage('leggings3', 'leggings3').hint,
  },

  // Women's Lingerie
  {
    id: 'lingerie_001',
    name: 'Lace Bralette',
    description: 'A delicate and beautiful lace bralette.',
    longDescription: 'This intricate lace bralette is both comfortable and stylish, perfect for everyday wear or a special occasion.',
    price: 50.00,
    image: getImage('lingerie1', 'lingerie1').url,
    imageHint: getImage('lingerie1', 'lingerie1').hint,
  },
  {
    id: 'lingerie_002',
    name: 'Silk Lingerie Set',
    description: 'A luxurious and elegant silk lingerie set.',
    longDescription: 'Feel exquisite in this matching lingerie set made from pure, soft silk.',
    price: 120.00,
    image: getImage('lingerie2', 'lingerie2').url,
    imageHint: getImage('lingerie2', 'lingerie2').hint,
  },
  {
    id: 'lingerie_003',
    name: 'Seamless Underwear Set',
    description: 'A comfortable and invisible seamless underwear set.',
    longDescription: 'This seamless underwear set is perfect for a smooth and invisible look under any outfit.',
    price: 60.00,
    image: getImage('lingerie3', 'lingerie3').url,
    imageHint: getImage('lingerie3', 'lingerie3').hint,
  },

  // Men's Jackets
  {
    id: 'men_jacket_001',
    name: 'Men\'s Denim Jacket',
    description: 'A classic blue denim jacket for men.',
    longDescription: 'This versatile denim jacket is a timeless piece for any man\'s wardrobe, perfect for a casual look.',
    price: 95.00,
    image: getImage('men_jacket_1', 'menjacket1').url,
    imageHint: getImage('men_jacket_1', 'menjacket1').hint,
  },
  {
    id: 'men_jacket_002',
    name: 'Men\'s Leather Jacket',
    description: 'A sleek black leather jacket for men.',
    longDescription: 'This classic black leather jacket adds a cool and edgy vibe to any outfit.',
    price: 180.00,
    image: getImage('men_jacket_2', 'menjacket2').url,
    imageHint: getImage('men_jacket_2', 'menjacket2').hint,
  },
  {
    id: 'men_jacket_003',
    name: 'Men\'s Bomber Jacket',
    description: 'A stylish green bomber jacket for men.',
    longDescription: 'Stay on-trend with this green bomber jacket, perfect for a modern and casual style.',
    price: 120.00,
    image: getImage('men_jacket_3', 'menjacket3').url,
    imageHint: getImage('men_jacket_3', 'menjacket3').hint,
  },

  // Men's Pants
  {
    id: 'men_pants_001',
    name: 'Men\'s Blue Jeans',
    description: 'A classic pair of blue jeans for men.',
    longDescription: 'These timeless blue jeans are a wardrobe staple, offering a comfortable and versatile fit.',
    price: 70.00,
    image: getImage('men_pants_1', 'menpants1').url,
    imageHint: getImage('men_pants_1', 'menpants1').hint,
  },
  {
    id: 'men_pants_002',
    name: 'Men\'s Chino Pants',
    description: 'Stylish khaki chino pants for men.',
    longDescription: 'These khaki chino pants are perfect for a smart-casual look, offering both style and comfort.',
    price: 65.00,
    image: getImage('men_pants_2', 'menpants2').url,
    imageHint: getImage('men_pants_2', 'menpants2').hint,
  },
  {
    id: 'men_pants_003',
    name: 'Men\'s Sweatpants',
    description: 'Comfortable gray sweatpants for men.',
    longDescription: 'These soft and comfortable gray sweatpants are perfect for lounging or a casual day out.',
    price: 50.00,
    image: getImage('men_pants_3', 'menpants3').url,
    imageHint: getImage('men_pants_3', 'menpants3').hint,
  },

  // Men's T-Shirts
  {
    id: 'men_tshirt_001',
    name: 'Men\'s Black T-Shirt',
    description: 'A classic black crewneck t-shirt for men.',
    longDescription: 'This essential black t-shirt is made from soft cotton, perfect for any casual occasion.',
    price: 25.00,
    image: getImage('men_tshirt_1', 'mentshirt1').url,
    imageHint: getImage('men_tshirt_1', 'mentshirt1').hint,
  },
  {
    id: 'men_tshirt_002',
    name: 'Men\'s V-Neck T-Shirt',
    description: 'A stylish gray v-neck t-shirt for men.',
    longDescription: 'This gray v-neck t-shirt offers a modern fit and is made from a comfortable cotton blend.',
    price: 28.00,
    image: getImage('men_tshirt_2', 'mentshirt2').url,
    imageHint: getImage('men_tshirt_2', 'mentshirt2').hint,
  },
  {
    id: 'men_tshirt_003',
    name: 'Men\'s Striped T-Shirt',
    description: 'A casual striped pocket t-shirt for men.',
    longDescription: 'This striped t-shirt with a pocket detail is a stylish and casual choice for everyday wear.',
    price: 32.00,
    image: getImage('men_tshirt_3', 'mentshirt3').url,
    imageHint: getImage('men_tshirt_3', 'mentshirt3').hint,
  },

  // Men's Shirts
  {
    id: 'men_shirt_001',
    name: 'Men\'s Dress Shirt',
    description: 'A classic white dress shirt for men.',
    longDescription: 'This crisp white dress shirt is perfect for formal occasions or a professional look.',
    price: 60.00,
    image: getImage('men_shirt_1', 'menshirt1').url,
    imageHint: getImage('men_shirt_1', 'menshirt1').hint,
  },
  {
    id: 'men_shirt_002',
    name: 'Men\'s Flannel Shirt',
    description: 'A casual plaid flannel shirt for men.',
    longDescription: 'Stay warm and stylish with this classic plaid flannel shirt, perfect for a rugged, outdoor look.',
    price: 55.00,
    image: getImage('men_shirt_2', 'menshirt2').url,
    imageHint: getImage('men_shirt_2', 'menshirt2').hint,
  },
  {
    id: 'men_shirt_003',
    name: 'Men\'s Button-Up Shirt',
    description: 'A blue short-sleeve button-up shirt for men.',
    longDescription: 'This short-sleeve button-up shirt is perfect for warm weather and a relaxed, casual style.',
    price: 45.00,
    image: getImage('men_shirt_3', 'menshirt3').url,
    imageHint: getImage('men_shirt_3', 'menshirt3').hint,
  },

  // Men's Underwear
  {
    id: 'men_underwear_001',
    name: 'Men\'s Boxer Briefs',
    description: 'A pack of comfortable cotton boxer briefs for men.',
    longDescription: 'These boxer briefs are made from a soft and breathable cotton blend for all-day comfort.',
    price: 35.00,
    image: getImage('men_underwear_1', 'menunderwear1').url,
    imageHint: getImage('men_underwear_1', 'menunderwear1').hint,
  },
  {
    id: 'men_underwear_002',
    name: 'Men\'s White Briefs',
    description: 'A set of classic white briefs for men.',
    longDescription: 'These classic white briefs offer a secure and comfortable fit for everyday wear.',
    price: 30.00,
    image: getImage('men_underwear_2', 'menunderwear2').url,
    imageHint: getImage('men_underwear_2', 'menunderwear2').hint,
  },
  {
    id: 'men_underwear_003',
    name: 'Men\'s Boxer Shorts',
    description: 'A pair of patterned boxer shorts for men.',
    longDescription: 'These fun patterned boxer shorts are made from lightweight cotton for a comfortable fit.',
    price: 25.00,
    image: getImage('men_underwear_3', 'menunderwear3').url,
    imageHint: getImage('men_underwear_3', 'menunderwear3').hint,
  },

  // Collection - Jumpsuits
  {
    id: 'jumpsuit_001',
    name: 'Denim Jumpsuit',
    description: 'A stylish and versatile denim jumpsuit.',
    longDescription: 'This denim jumpsuit features a modern cut and is perfect for a chic, all-in-one outfit.',
    price: 110.00,
    image: getImage('jumpsuit1', 'jumpsuit1').url,
    imageHint: getImage('jumpsuit1', 'jumpsuit1').hint,
  },
  {
    id: 'jumpsuit_002',
    name: 'Elegant Black Jumpsuit',
    description: 'A sophisticated black jumpsuit for any occasion.',
    longDescription: 'This elegant black jumpsuit is a perfect alternative to a dress for formal events.',
    price: 130.00,
    image: getImage('jumpsuit2', 'jumpsuit2').url,
    imageHint: getImage('jumpsuit2', 'jumpsuit2').hint,
  },
  {
    id: 'jumpsuit_003',
    name: 'Floral Print Jumpsuit',
    description: 'A casual and fun floral print jumpsuit.',
    longDescription: 'This floral jumpsuit is made from a lightweight fabric, ideal for warm weather and a relaxed vibe.',
    price: 90.00,
    image: getImage('jumpsuit3', 'jumpsuit3').url,
    imageHint: getImage('jumpsuit3', 'jumpsuit3').hint,
  },

  // Collection - Polo T-shirts
  {
    id: 'polo_t_shirt_001',
    name: 'Classic Navy Polo',
    description: 'A timeless navy blue polo t-shirt.',
    longDescription: 'This classic polo is made from breathable cotton piqué, perfect for a smart-casual look.',
    price: 50.00,
    image: getImage('polo1', 'polo1').url,
    imageHint: getImage('polo1', 'polo1').hint,
  },
  {
    id: 'polo_t_shirt_002',
    name: 'Bright Red Polo',
    description: 'A vibrant red polo t-shirt.',
    longDescription: 'Make a statement with this bright red polo, crafted for a comfortable and stylish fit.',
    price: 52.00,
    image: getImage('polo2', 'polo2').url,
    imageHint: getImage('polo2', 'polo2').hint,
  },
  {
    id: 'polo_t_shirt_003',
    name: 'Striped Polo Shirt',
    description: 'A modern striped polo t-shirt.',
    longDescription: 'This striped polo adds a contemporary twist to a classic design, perfect for any casual occasion.',
    price: 55.00,
    image: getImage('polo3', 'polo3').url,
    imageHint: getImage('polo3', 'polo3').hint,
  },

  // Collection - Womens Beachwear
  {
    id: 'womens_beachwear_001',
    name: 'One-Piece Swimsuit',
    description: 'A vibrant and stylish one-piece swimsuit.',
    longDescription: 'This one-piece swimsuit features a flattering cut and a bold color to make you stand out at the beach.',
    price: 80.00,
    image: getImage('wbeach1', 'wbeach1').url,
    imageHint: getImage('wbeach1', 'wbeach1').hint,
  },
  {
    id: 'womens_beachwear_002',
    name: 'Bikini Set',
    description: 'A chic and modern bikini set.',
    longDescription: 'This stylish bikini set is perfect for sunbathing and swimming, offering a comfortable and fashionable fit.',
    price: 75.00,
    image: getImage('wbeach2', 'wbeach2').url,
    imageHint: getImage('wbeach2', 'wbeach2').hint,
  },
  {
    id: 'womens_beachwear_003',
    name: 'Beach Cover-Up',
    description: 'A breezy and elegant beach cover-up.',
    longDescription: 'This lightweight cover-up is perfect for throwing over your swimsuit, taking you from the beach to the bar.',
    price: 60.00,
    image: getImage('wbeach3', 'wbeach3').url,
    imageHint: getImage('wbeach3', 'wbeach3').hint,
  },

  // Collection - Mens Beachwear
  {
    id: 'mens_beachwear_001',
    name: 'Board Shorts',
    description: 'Classic and comfortable board shorts.',
    longDescription: 'These board shorts are designed for comfort and performance, perfect for surfing or relaxing by the pool.',
    price: 50.00,
    image: getImage('mbeach1', 'mbeach1').url,
    imageHint: getImage('mbeach1', 'mbeach1').hint,
  },
  {
    id: 'mens_beachwear_002',
    name: 'Swim Trunks',
    description: 'Stylish and modern swim trunks.',
    longDescription: 'These swim trunks feature a modern cut and quick-drying fabric, perfect for a day at the beach.',
    price: 45.00,
    image: getImage('mbeach2', 'mbeach2').url,
    imageHint: getImage('mbeach2', 'mbeach2').hint,
  },
  {
    id: 'mens_beachwear_003',
    name: 'Rash Guard',
    description: 'A protective and lightweight rash guard.',
    longDescription: 'This rash guard offers UV protection and is made from a quick-drying material, ideal for water sports.',
    price: 55.00,
    image: getImage('mbeach3', 'mbeach3').url,
    imageHint: getImage('mbeach3', 'mbeach3').hint,
  },

  // Collection - New Arrivals
  {
    id: 'new_arrivals_001',
    name: 'Stylish Trench Coat',
    description: 'A new addition to our coat collection.',
    longDescription: 'This newly arrived trench coat is a modern take on a classic design, perfect for any season.',
    price: 190.00,
    image: getImage('newarrival1', 'newarrival1').url,
    imageHint: getImage('newarrival1', 'newarrival1').hint,
  },
  {
    id: 'new_arrivals_002',
    name: 'Summer Sandals',
    description: 'Brand new sandals for the summer season.',
    longDescription: 'Just in for summer, these stylish sandals are perfect for warm weather and beach days.',
    price: 65.00,
    image: getImage('newarrival2', 'newarrival2').url,
    imageHint: getImage('newarrival2', 'newarrival2').hint,
  },

  // Collection - New Catalog
  {
    id: 'new_catalog_001',
    name: 'Catalog Exclusive Item',
    description: 'An exclusive item from our new catalog.',
    longDescription: 'Discover this exclusive piece from our latest catalog, featuring premium materials and design.',
    price: 250.00,
    image: getImage('newcatalog1', 'newcatalog1').url,
    imageHint: getImage('newcatalog1', 'newcatalog1').hint,
  },
  // Sports - Athletics
  {
    id: 'athletics_001',
    name: 'Pro Running Shoes',
    description: 'High-performance running shoes.',
    longDescription: 'Engineered for speed and comfort, these running shoes are perfect for competitive athletics.',
    price: 130.00,
    image: getImage('athletics1', 'athletics1').url,
    imageHint: getImage('athletics1', 'athletics1').hint,
  },
  {
    id: 'athletics_002',
    name: 'Performance Shorts',
    description: 'Moisture-wicking athletic shorts.',
    longDescription: 'Stay dry and comfortable during intense workouts with these moisture-wicking athletic shorts.',
    price: 45.00,
    image: getImage('athletics2', 'athletics2').url,
    imageHint: getImage('athletics2', 'athletics2').hint,
  },
  // Sports - Basketball
  {
    id: 'basketball_001',
    name: 'Official Basketball',
    description: 'A professional-grade basketball.',
    longDescription: 'The official size and weight basketball for serious players, with superior grip and durability.',
    price: 40.00,
    image: getImage('basketball1', 'basketball1').url,
    imageHint: getImage('basketball1', 'basketball1').hint,
  },
  {
    id: 'basketball_002',
    name: 'Team Basketball Jersey',
    description: 'A stylish basketball jersey.',
    longDescription: 'Represent your team with this breathable and lightweight basketball jersey, available in multiple colors.',
    price: 60.00,
    image: getImage('basketball2', 'basketball2').url,
    imageHint: getImage('basketball2', 'basketball2').hint,
  },
  // Sports - Boxing
  {
    id: 'boxing_001',
    name: 'Professional Boxing Gloves',
    description: 'Professional boxing gloves.',
    longDescription: 'These professional-grade boxing gloves provide excellent protection and support for training and competition.',
    price: 80.00,
    image: getImage('boxing1', 'boxing1').url,
    imageHint: getImage('boxing1', 'boxing1').hint,
  },
  {
    id: 'boxing_002',
    name: 'Boxing Hand Wraps',
    description: 'A set of hand wraps for boxing.',
    longDescription: 'Protect your hands and wrists with these durable and supportive hand wraps, essential for any boxer.',
    price: 15.00,
    image: getImage('boxing2', 'boxing2').url,
    imageHint: getImage('boxing2', 'boxing2').hint,
  },
  // Sports - Cycling
  {
    id: 'cycling_001',
    name: 'Aero Cycling Helmet',
    description: 'A lightweight cycling helmet.',
    longDescription: 'This aerodynamic cycling helmet provides excellent protection and ventilation for long rides.',
    price: 120.00,
    image: getImage('cycling1', 'cycling1').url,
    imageHint: getImage('cycling1', 'cycling1').hint,
  },
  {
    id: 'cycling_002',
    name: 'Padded Cycling Shorts',
    description: 'Padded cycling shorts for comfort.',
    longDescription: 'These padded cycling shorts are designed for maximum comfort on long rides, reducing chafing and discomfort.',
    price: 70.00,
    image: getImage('cycling2', 'cycling2').url,
    imageHint: getImage('cycling2', 'cycling2').hint,
  },
  // Sports - Dance Wear
  {
    id: 'dancewear_001',
    name: 'Classic Leotard',
    description: 'A classic ballet leotard.',
    longDescription: 'A comfortable and elegant leotard, perfect for ballet and other forms of dance.',
    price: 40.00,
    image: getImage('dancewear1', 'dancewear1').url,
    imageHint: getImage('dancewear1', 'dancewear1').hint,
  },
  {
    id: 'dancewear_002',
    name: 'Ballet Shoes',
    description: 'A pair of comfortable ballet shoes.',
    longDescription: 'These ballet shoes offer a perfect fit and support for dancers of all levels.',
    price: 35.00,
    image: getImage('dancewear2', 'dancewear2').url,
    imageHint: getImage('dancewear2', 'dancewear2').hint,
  },
  // Sports - Golf
  {
    id: 'golf_001',
    name: 'Pro Golf Club Set',
    description: 'A set of professional golf clubs.',
    longDescription: 'This complete set of golf clubs is designed for performance and precision, suitable for all skill levels.',
    price: 500.00,
    image: getImage('golf1', 'golf1').url,
    imageHint: getImage('golf1', 'golf1').hint,
  },
  {
    id: 'golf_002',
    name: 'Performance Golf Polo',
    description: 'A classic golf polo shirt.',
    longDescription: 'Stay cool and comfortable on the course with this performance golf polo, made from moisture-wicking fabric.',
    price: 55.00,
    image: getImage('golf2', 'golf2').url,
    imageHint: getImage('golf2', 'golf2').hint,
  },
  // Sports - Hockey
  {
    id: 'hockey_001',
    name: 'Composite Hockey Stick',
    description: 'A durable hockey stick.',
    longDescription: 'This lightweight and durable composite hockey stick is designed for powerful shots and precise control.',
    price: 150.00,
    image: getImage('hockey1', 'hockey1').url,
    imageHint: getImage('hockey1', 'hockey1').hint,
  },
  {
    id: 'hockey_002',
    name: 'Protective Hockey Pads',
    description: 'A set of protective hockey pads.',
    longDescription: 'This set of hockey pads provides complete protection for shins, elbows, and shoulders.',
    price: 200.00,
    image: getImage('hockey2', 'hockey2').url,
    imageHint: getImage('hockey2', 'hockey2').hint,
  },
  // Sports - Marathons
  {
    id: 'marathon_001',
    name: 'Hydration Running Pack',
    description: 'A hydration pack for long runs.',
    longDescription: 'Stay hydrated during long-distance runs with this lightweight and comfortable hydration pack.',
    price: 60.00,
    image: getImage('marathon1', 'marathon1').url,
    imageHint: getImage('marathon1', 'marathon1').hint,
  },
  {
    id: 'marathon_002',
    name: 'Marathon Running Shorts',
    description: 'Lightweight running shorts for marathons.',
    longDescription: 'These lightweight and breathable running shorts are designed for maximum comfort during marathons.',
    price: 50.00,
    image: getImage('marathon2', 'marathon2').url,
    imageHint: getImage('marathon2', 'marathon2').hint,
  },
  // Sports - Tennis
  {
    id: 'tennis_001',
    name: 'Pro Tennis Racket',
    description: 'A high-performance tennis racket.',
    longDescription: 'This high-performance tennis racket offers a great balance of power and control for competitive players.',
    price: 180.00,
    image: getImage('tennis1', 'tennis1').url,
    imageHint: getImage('tennis1', 'tennis1').hint,
  },
  {
    id: 'tennis_002',
    name: 'Championship Tennis Balls',
    description: 'A can of professional tennis balls.',
    longDescription: 'This can of championship-quality tennis balls is perfect for matches and practice sessions.',
    price: 5.00,
    image: getImage('tennis2', 'tennis2').url,
    imageHint: getImage('tennis2', 'tennis2').hint,
  },
  // Sports - Triathlon
  {
    id: 'triathlon_001',
    name: 'Performance Wetsuit',
    description: 'A full-body wetsuit for triathlons.',
    longDescription: 'This full-body wetsuit provides buoyancy and thermal protection for the swimming leg of a triathlon.',
    price: 250.00,
    image: getImage('triathlon1', 'triathlon1').url,
    imageHint: getImage('triathlon1', 'triathlon1').hint,
  },
  {
    id: 'triathlon_002',
    name: 'Aero Tri-Suit',
    description: 'A comfortable and aerodynamic tri-suit.',
    longDescription: 'This tri-suit is designed for performance across all three disciplines of a triathlon, offering comfort and aerodynamics.',
    price: 200.00,
    image: getImage('triathlon2', 'triathlon2').url,
    imageHint: getImage('triathlon2', 'triathlon2').hint,
  },
    // Custom Clothing - White Label
  {
    id: 'whitelabel_001',
    name: 'White Label T-Shirt',
    description: 'High-quality plain t-shirt for your brand.',
    longDescription: 'A premium, unbranded t-shirt made from 100% ring-spun cotton, ready for your custom labels and designs. Perfect for starting your own clothing line.',
    price: 15.00,
    image: getImage('whitelabel1', 'whitelabel1').url,
    imageHint: getImage('whitelabel1', 'whitelabel1').hint,
  },
  {
    id: 'whitelabel_002',
    name: 'White Label Hoodie',
    description: 'Plush, unbranded hoodie.',
    longDescription: 'A comfortable and stylish hoodie made from a soft cotton-poly blend. Features a kangaroo pocket and double-lined hood, ready for your branding.',
    price: 40.00,
    image: getImage('whitelabel2', 'whitelabel2').url,
    imageHint: getImage('whitelabel2', 'whitelabel2').hint,
  },
  {
    id: 'whitelabel_003',
    name: 'White Label Polo Shirt',
    description: 'Classic unbranded polo shirt.',
    longDescription: 'A high-quality piqué polo shirt with a ribbed collar and cuffs. Ideal for corporate branding or a sophisticated clothing line.',
    price: 25.00,
    image: getImage('whitelabel3', 'whitelabel3').url,
    imageHint: getImage('whitelabel3', 'whitelabel3').hint,
  },
  {
    id: 'whitelabel_004',
    name: 'White Label Sweatshirt',
    description: 'Cozy, plain sweatshirt.',
    longDescription: 'A classic crewneck sweatshirt made from a durable fleece fabric. A perfect canvas for your custom graphics and branding.',
    price: 35.00,
    image: getImage('whitelabel4', 'whitelabel4').url,
    imageHint: getImage('whitelabel4', 'whitelabel4').hint,
  },
  {
    id: 'whitelabel_005',
    name: 'White Label Tote Bag',
    description: 'Durable, unbranded cotton tote bag.',
    longDescription: 'A sturdy and spacious tote bag made from heavy-duty cotton canvas, perfect for custom printing and branding.',
    price: 12.00,
    image: getImage('whitelabel5', 'whitelabel5').url,
    imageHint: getImage('whitelabel5', 'whitelabel5').hint,
  },
  {
    id: 'whitelabel_006',
    name: 'White Label Baseball Cap',
    description: 'Blank cap for embroidery.',
    longDescription: 'A classic six-panel baseball cap with an adjustable strap, ready for your custom logo embroidery.',
    price: 10.00,
    image: getImage('whitelabel6', 'whitelabel6').url,
    imageHint: getImage('whitelabel6', 'whitelabel6').hint,
  },
  {
    id: 'whitelabel_007',
    name: 'White Label Leggings',
    description: 'High-quality plain leggings.',
    longDescription: 'Stretchy and comfortable leggings made from a premium spandex blend, perfect for fitness or fashion branding.',
    price: 28.00,
    image: getImage('whitelabel7', 'whitelabel7').url,
    imageHint: getImage('whitelabel7', 'whitelabel7').hint,
  },
  {
    id: 'whitelabel_008',
    name: 'White Label Joggers',
    description: 'Comfortable, unbranded joggers.',
    longDescription: 'Stylish and comfortable joggers with an adjustable waistband and tapered fit, ready for your custom branding.',
    price: 38.00,
    image: getImage('whitelabel8', 'whitelabel8').url,
    imageHint: getImage('whitelabel8', 'whitelabel8').hint,
  },

  // Custom Clothing - Sublimation
  {
    id: 'sublimation_001',
    name: 'Sublimation T-Shirt',
    description: '100% polyester t-shirt for sublimation.',
    longDescription: 'A high-quality, 100% polyester t-shirt specifically designed for vibrant and durable sublimation printing. Soft and moisture-wicking.',
    price: 18.00,
    image: getImage('sublimation1', 'sublimation1').url,
    imageHint: getImage('sublimation1', 'sublimation1').hint,
  },
  {
    id: 'sublimation_002',
    name: 'Sublimation Mug',
    description: 'Ceramic mug with sublimation coating.',
    longDescription: 'A classic ceramic mug with a special coating that ensures your sublimation prints are bright and long-lasting. Dishwasher and microwave safe.',
    price: 8.00,
    image: getImage('sublimation2', 'sublimation2').url,
    imageHint: getImage('sublimation2', 'sublimation2').hint,
  },
  {
    id: 'sublimation_003',
    name: 'Sublimation Phone Case',
    description: 'Blank phone case for custom printing.',
    longDescription: 'A durable, blank phone case with a metal insert for high-quality sublimation printing. Available for various phone models.',
    price: 10.00,
    image: getImage('sublimation3', 'sublimation3').url,
    imageHint: getImage('sublimation3', 'sublimation3').hint,
  },
  {
    id: 'sublimation_004',
    name: 'Sublimation Mouse Pad',
    description: 'Blank mouse pad for custom designs.',
    longDescription: 'A non-slip rubber mouse pad with a polyester top layer, perfect for creating custom designs with sublimation.',
    price: 6.00,
    image: getImage('sublimation4', 'sublimation4').url,
    imageHint: getImage('sublimation4', 'sublimation4').hint,
  },
  {
    id: 'sublimation_005',
    name: 'Sublimation Hoodie',
    description: 'Polyester hoodie for vibrant prints.',
    longDescription: 'A 100% polyester hoodie designed for all-over sublimation printing, allowing for bold and vibrant designs.',
    price: 45.00,
    image: getImage('sublimation5', 'sublimation5').url,
    imageHint: getImage('sublimation5', 'sublimation5').hint,
  },
  {
    id: 'sublimation_006',
    name: 'Sublimation Socks',
    description: 'Blank socks ready for custom printing.',
    longDescription: 'Create unique, custom socks with these polyester-blend blanks, perfect for vibrant sublimation prints.',
    price: 9.00,
    image: getImage('sublimation6', 'sublimation6').url,
    imageHint: getImage('sublimation6', 'sublimation6').hint,
  },
  {
    id: 'sublimation_007',
    name: 'Sublimation Tote Bag',
    description: 'Polyester tote for all-over prints.',
    longDescription: 'A durable polyester tote bag that is perfect for creating custom, all-over sublimation prints.',
    price: 14.00,
    image: getImage('sublimation7', 'sublimation7').url,
    imageHint: getImage('sublimation7', 'sublimation7').hint,
  },
  {
    id: 'sublimation_008',
    name: 'Sublimation Sports Jersey',
    description: 'Performance jersey for team branding.',
    longDescription: 'A moisture-wicking, 100% polyester sports jersey, ideal for creating custom team uniforms with sublimation printing.',
    price: 30.00,
    image: getImage('sublimation8', 'sublimation8').url,
    imageHint: getImage('sublimation8', 'sublimation8').hint,
  },

  // Kids - Girls Dresses
  {
    id: 'girls_dress_001',
    name: 'Pink Party Dress',
    description: 'A cute pink party dress for girls.',
    longDescription: 'This adorable pink party dress is perfect for special occasions, featuring a tulle skirt and sparkly details.',
    price: 45.00,
    image: getImage('girls_dress_1', 'girlsdress1').url,
    imageHint: getImage('girls_dress_1', 'girlsdress1').hint,
  },
  {
    id: 'girls_dress_002',
    name: 'Floral Print Dress',
    description: 'A casual floral print dress for girls.',
    longDescription: 'A comfortable and stylish floral dress, perfect for everyday wear and warm weather.',
    price: 35.00,
    image: getImage('girls_dress_2', 'girlsdress2').url,
    imageHint: getImage('girls_dress_2', 'girlsdress2').hint,
  },
  {
    id: 'girls_dress_003',
    name: 'Denim Dress',
    description: 'A stylish and durable denim dress for girls.',
    longDescription: 'This denim dress is both fashionable and durable, ideal for school or play.',
    price: 40.00,
    image: getImage('girls_dress_3', 'girlsdress3').url,
    imageHint: getImage('girls_dress_3', 'girlsdress3').hint,
  },

  // Kids - Infants (0-24 months)
  {
    id: 'infant_001',
    name: 'Soft Cotton Onesie',
    description: 'A pack of soft cotton onesies for infants.',
    longDescription: 'Made from 100% organic cotton, these onesies are gentle on your baby\'s skin and perfect for everyday wear.',
    price: 25.00,
    image: getImage('infant_1', 'infant1').url,
    imageHint: getImage('infant_1', 'infant1').hint,
  },
  {
    id: 'infant_002',
    name: 'Infant Bibs Set',
    description: 'A set of cute and practical infant bibs.',
    longDescription: 'Keep your baby clean and dry with this set of absorbent cotton bibs, featuring adorable designs.',
    price: 15.00,
    image: getImage('infant_2', 'infant2').url,
    imageHint: getImage('infant_2', 'infant2').hint,
  },
  {
    id: 'infant_003',
    name: 'Warm Sleep Sack',
    description: 'A cozy and safe sleep sack for infants.',
    longDescription: 'This warm sleep sack keeps your baby comfortable and secure all night long, promoting better sleep.',
    price: 30.00,
    image: getImage('infant_3', 'infant3').url,
    imageHint: getImage('infant_3', 'infant3').hint,
  },

  // Kids - Toddlers (2-4 Yrs)
  {
    id: 'toddler_001',
    name: 'Playful T-Shirt',
    description: 'A fun and playful t-shirt for toddlers.',
    longDescription: 'This t-shirt features a fun graphic and is made from soft, durable cotton, perfect for active toddlers.',
    price: 20.00,
    image: getImage('toddler_1', 'toddler1').url,
    imageHint: getImage('toddler_1', 'toddler1').hint,
  },
  {
    id: 'toddler_002',
    name: 'Toddler Leggings',
    description: 'A pair of comfortable and stretchy leggings for toddlers.',
    longDescription: 'These comfortable leggings are perfect for playtime, made from a stretchy cotton blend that moves with your toddler.',
    price: 18.00,
    image: getImage('toddler_2', 'toddler2').url,
    imageHint: getImage('toddler_2', 'toddler2').hint,
  },
  {
    id: 'toddler_003',
    name: 'Cute Toddler Hoodie',
    description: 'A cute and cozy hoodie for toddlers.',
    longDescription: 'This adorable hoodie will keep your toddler warm and stylish, featuring a fun design and soft fabric.',
    price: 35.00,
    image: getImage('toddler_3', 'toddler3').url,
    imageHint: getImage('toddler_3', 'toddler3').hint,
  },

  // Kids - Little (4-7 Yrs)
  {
    id: 'little_kid_001',
    name: 'Graphic T-Shirt',
    description: 'A fun graphic t-shirt for little kids.',
    longDescription: 'This cool graphic t-shirt is perfect for school and play, made from 100% comfortable cotton.',
    price: 22.00,
    image: getImage('little_kid_1', 'littlekid1').url,
    imageHint: getImage('little_kid_1', 'littlekid1').hint,
  },
  {
    id: 'little_kid_002',
    name: 'Durable Kids Jeans',
    description: 'A pair of durable and stylish jeans for little kids.',
    longDescription: 'These jeans are built to last, perfect for active kids, and feature an adjustable waistband for a great fit.',
    price: 40.00,
    image: getImage('little_kid_2', 'littlekid2').url,
    imageHint: getImage('little_kid_2', 'littlekid2').hint,
  },
  {
    id: 'little_kid_003',
    name: 'Cozy Kids Sweater',
    description: 'A warm and cozy sweater for little kids.',
    longDescription: 'This stylish sweater is perfect for cooler days, made from a soft and comfortable knit fabric.',
    price: 38.00,
    image: getImage('little_kid_3', 'littlekid3').url,
    imageHint: getImage('little_kid_3', 'littlekid3').hint,
  }
];

export const getProductById = (id: string): Product | undefined => {
  return allProducts.find(p => p.id === id);
}
